import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import { ThemeProvider } from "@/Components/ThemeProvider";
import Clientproviders from "@/Components/Clientproviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // helps us to handle user session
    // for server session, we have nextAuth, middleware
    <Clientproviders>
    <html lang="en">
      {/* inter is nothing but a font */}
      <body className={inter.className}> 
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
        <Header/>
        {children}
      </ThemeProvider>
      </body>
    </html>
    </Clientproviders>
  );
}
